In [1]:
import pandas as pd

In [2]:
labels = ['p','q','r']
my_list = [10,20,30]
d = {'p':10,'q':20,'r':30}

In [3]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(data=my_list,index=labels)

p    10
q    20
r    30
dtype: int64

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(labels,my_list)

10    p
20    q
30    r
dtype: object

In [7]:
d

{'p': 10, 'q': 20, 'r': 30}

In [8]:
pd.Series(d.values(),index=[2,3,4])

2    10
3    20
4    30
dtype: int64

In [9]:
ser1= pd.Series([1,2,3,4],index=['USA','GERMAN','CHINA','JAPAN'])
ser1

USA       1
GERMAN    2
CHINA     3
JAPAN     4
dtype: int64

In [10]:
ser2= pd.Series([1,2,3,4],index=['JAPAN','USA','AFRICA','GERMAN'])
ser2

JAPAN     1
USA       2
AFRICA    3
GERMAN    4
dtype: int64

In [11]:
ser1+ser2

AFRICA    NaN
CHINA     NaN
GERMAN    6.0
JAPAN     5.0
USA       3.0
dtype: float64

In [12]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [13]:
data=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]

In [14]:
df = pd.DataFrame(data, index='A B C D E'.split(),columns=['w','x','y','z'])

In [15]:
df

w   x   y   z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20

In [16]:
print(df)

    w   x   y   z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20


In [17]:
df['x']

A     2
B     6
C    10
D    14
E    18
Name: x, dtype: int64

In [18]:
type(df['x'])

pandas.core.series.Series

In [19]:
list(df.columns)

['w', 'x', 'y', 'z']

In [20]:
df[['x','y','z',]]

x   y   z
A   2   3   4
B   6   7   8
C  10  11  12
D  14  15  16
E  18  19  20

In [21]:
df['w']+df['y']+df['x']+df['z']

A    10
B    26
C    42
D    58
E    74
dtype: int64

In [22]:
df['new']=df['w']+df['y']+df['x']+df['z']
df['new1']=[9,8,7,6,4]

In [23]:
df

w   x   y   z  new  new1
A   1   2   3   4   10     9
B   5   6   7   8   26     8
C   9  10  11  12   42     7
D  13  14  15  16   58     6
E  17  18  19  20   74     4

In [24]:
df.drop('new',axis=1)

w   x   y   z  new1
A   1   2   3   4     9
B   5   6   7   8     8
C   9  10  11  12     7
D  13  14  15  16     6
E  17  18  19  20     4

In [25]:
df.drop('new',axis=1,inplace=True)
df

w   x   y   z  new1
A   1   2   3   4     9
B   5   6   7   8     8
C   9  10  11  12     7
D  13  14  15  16     6
E  17  18  19  20     4

In [26]:
df.drop('B')

w   x   y   z  new1
A   1   2   3   4     9
C   9  10  11  12     7
D  13  14  15  16     6
E  17  18  19  20     4

In [27]:
df

w   x   y   z  new1
A   1   2   3   4     9
B   5   6   7   8     8
C   9  10  11  12     7
D  13  14  15  16     6
E  17  18  19  20     4

In [28]:
df.loc['C']

w        9
x       10
y       11
z       12
new1     7
Name: C, dtype: int64

In [29]:
df.iloc[4]

w       17
x       18
y       19
z       20
new1     4
Name: E, dtype: int64

In [30]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [31]:
pip install seaborn


Note: you may need to restart the kernel to use updated packages.


In [33]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('User_Data.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [36]:
dataset['Gender'] = dataset['Gender'].map({'Male': 0,'Female': 1, }).astype(float)
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510     0.0   19            19000          0
1    15810944     0.0   35            20000          0
2    15668575     1.0   26            43000          0
3    15603246     1.0   27            57000          0
4    15804002     0.0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863     1.0   46            41000          1
396  15706071     0.0   51            23000          1
397  15654296     1.0   50            20000          1
398  15755018     0.0   36            33000          0
399  15594041     1.0   49            36000          1

[400 rows x 5 columns]

In [35]:
x = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,4].values

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [6]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [7]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25)

In [8]:
ytrain

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1])

In [9]:
xtrain

array([[    46,  88000],
       [    41,  72000],
       [    31,  89000],
       [    58, 144000],
       [    43, 129000],
       [    42,  54000],
       [    18,  86000],
       [    41,  30000],
       [    27,  54000],
       [    30,  79000],
       [    35,  72000],
       [    26,  15000],
       [    37,  75000],
       [    45,  22000],
       [    27,  88000],
       [    24,  23000],
       [    42,  65000],
       [    39,  75000],
       [    48,  33000],
       [    38,  61000],
       [    36,  99000],
       [    37,  93000],
       [    41,  51000],
       [    23,  28000],
       [    46,  79000],
       [    36,  60000],
       [    42,  70000],
       [    40,  71000],
       [    46,  23000],
       [    59,  88000],
       [    37,  71000],
       [    33, 149000],
       [    42,  64000],
       [    49,  28000],
       [    33, 113000],
       [    35,  60000],
       [    46,  74000],
       [    30,  87000],
       [    19,  70000],
       [    39,  71000],


In [10]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

print(xtrain[0:10, :])
print(xtest[0:10, :])

[[ 0.80447713  0.58021059]
 [ 0.32333052  0.09653382]
 [-0.6389627   0.61044039]
 [ 1.95922899  2.2730793 ]
 [ 0.51578916  1.81963232]
 [ 0.41955984 -0.44760255]
 [-1.88994388  0.519751  ]
 [ 0.32333052 -1.1731177 ]
 [-1.02387998 -0.44760255]
 [-0.73519202  0.30814241]]
[[ 0.99693577  0.15699342]
 [ 1.67054103  1.84986212]
 [-0.6389627  -1.53587528]
 [ 0.99693577 -1.02196871]
 [-0.73519202  1.15457676]
 [-0.83142134  2.39399849]
 [ 0.70824781  1.88009192]
 [-1.21633863  0.5499808 ]
 [-0.06158677  0.27791261]
 [ 0.2271012  -0.35691315]]


In [11]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain,ytrain)

LogisticRegression(random_state=0)

In [12]:
import pickle
with open('Logistic_model.pk1', 'wb')as files:
    pickle.dump(classifier,files)
with open('Logistic_model.pk1', 'rb')as files:
    classifier = pickle.load(files)

In [13]:
y_pred = classifier.predict(xtest)
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)
print('confusion matrix : \n', cm)

confusion matrix : 
 [[53  6]
 [14 27]]


In [15]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(ytest, y_pred))

Accuracy: 0.8


In [16]:
from sklearn.metrics import precision_score
print("precion:", precision_score(ytest, ytest))

precion: 1.0


In [40]:
from sklearn.metrics import recall_score
print("Recallscore:", recall_score(ytest, ytest))

Recallscore: 1.0


#SVM

In [47]:
from sklearn.svm import SVC
SVM = SVC(kernel = 'linear',random_state = 0)
SVM.fit(xtrain,ytrain)

SVC(kernel='linear', random_state=0)

In [48]:
y_pred = SVM.predict(xtest)
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [49]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score
CM = confusion_matrix(ytest, y_pred)
print('confusion matrix : \n', CM)

confusion matrix : 
 [[53  6]
 [14 27]]


In [50]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(ytest, y_pred))

Accuracy: 0.8


In [51]:
from sklearn.metrics import precision_score
print("precion:", precision_score(ytest, ytest))

precion: 1.0


In [52]:
from sklearn.metrics import recall_score
print("Recallscore:", recall_score(ytest, ytest))

Recallscore: 1.0
